metas:
  - name: http_log
    columnNames: ["host", "uri", "method", "contentType", "reqByteSize", "respByteSize", "reqTime"]
    columnTypes: ["String", "String", "UInt8", "UInt8", "UInt64", "UInt64", "DateTime"]