metas:
  - name: users_log
    columnNames: ["host", "sessionId", "url", "method", "contentType", "reqByteSize", "respByteSize"]
    columnTypes: ["String", "Int32", "String", "UInt8", "UInt8", "UInt64", "UInt64"]